"use strict";const fs=require("fs"),path=require("path");const{createSuite}=require("./runner");const ROOT=path.resolve(__dirname,"..","..");
const NOUNSTEM_L=Object.freeze([["te-l","#0-0(te-l)li-0#","telli"],["ca-l","#0-0(ca-l)li-0#","calli"],["tle-l","#0-0(tle-l)li-0#","tlelli"],["cē-l","#0-0(cē-l)li-0#","cēlli"],["icpa-l","#0-0(icpa-l)li-0#","icpalli"],["cā-cā-l","#0-0(cā-cā-l)li-0#","cācālli"],["ah-co-l","#0-0(ah-co-l)li-0#","ahcolli"],["xā-l","#0-0(xā-l)li-0#","xālli"],["xi-l","#0-0(xi-l)li-0#","xilli"]]);
function finite(ctx,tense){return ctx.evaluateClassicalNahuatlVncApplication({sourceStem:"nemi",verbClass:"A",sourceValence:"intransitive",subject:"3sg",mood:"indicative",tense,requestedDerivation:"direct",requestedVoice:"active"});}
function ordinary(ctx,stem){const source=ctx.buildClassicalNahuatlOrdinaryNncSourceFrame({stem}),operation=ctx.buildClassicalNahuatlOrdinaryNncOperationFrame(source,{state:"absolutive",subject:"3sg",sentenceType:"statement",polarity:"positive"});return{source,result:ctx.requestClassicalOrdinaryNncResult(source,operation)};}
function run(ctx={}){const s=createSuite("classical_lesson57_jobs"),ledger=JSON.parse(fs.readFileSync(path.join(ROOT,"docs/ANDREWS_ATOM_LEDGER.json"),"utf8")),plan=JSON.parse(fs.readFileSync(path.join(ROOT,"docs/canvas-progress/lesson57-review-plan.json"),"utf8")),field=Object.fromEntries(ledger.codebook.atomTuple.map((name,index)=>[name,index])),atoms=ledger.atoms.filter(atom=>/^§57(?:\.|$)/u.test(atom[field.canvasSection])),grammar=atoms.filter(atom=>atom[field.force]==="grammar-bearing"),roles=new Set(["canonical-rule-or-alternation","applicability-or-constraint","derived-realization","source-structure-schema","result-projection"]),writing=grammar.filter(atom=>roles.has(atom[field.projectRole])),mapped=new Set(plan.groups.flatMap(group=>group.sections));
s.eq("Lesson 57 partitions every Canvas atom into technical-proof groups",{atoms:atoms.length,grammar:grammar.length,writing:writing.length,readingOnly:atoms.length-writing.length,sections:[...new Set(atoms.map(atom=>atom[field.canvasSection]))],unmapped:atoms.filter(atom=>!mapped.has(atom[field.canvasSection])).map(atom=>atom[field.atomId])},{atoms:440,grammar:318,writing:264,readingOnly:176,sections:plan.groups.flatMap(group=>group.sections),unmapped:[]});
const ownerIds=[...new Set(grammar.map(atom=>atom[field.semanticOwnerId]))].sort(),observations=ownerIds.map(ownerId=>{const owned=grammar.filter(atom=>atom[field.semanticOwnerId]===ownerId),source=fs.readFileSync(path.join(ROOT,owned[0][field.semanticOwnerReference]),"utf8"),spec=JSON.parse(source.match(/const spec = (\{[\s\S]*\});\nexport default/u)[1]);return{atoms:owned.length,exact:source.includes(`"ownerId": "${ownerId}"`)&&typeof ctx[`build${spec.prefix}Source`]==="function"&&typeof ctx[`evaluate${spec.prefix}`]==="function"&&typeof ctx[`is${spec.prefix}Result`]==="function"};});
s.eq("all grammar-bearing atoms retain registered semantic owners",{atoms:observations.reduce((sum,item)=>sum+item.atoms,0),owners:observations.length,invalid:observations.filter(item=>!item.exact).length},{atoms:318,owners:15,invalid:0});
const present=finite(ctx,"present"),contextual=ctx.interpretClassicalNahuatlVncContextualTime(present,{referenceTime:"past",eventRelation:"same",relationScope:"concatenation"}),copied=ctx.interpretClassicalNahuatlVncContextualTime(JSON.parse(JSON.stringify(present)),{referenceTime:"past",eventRelation:"same",relationScope:"concatenation"});
s.eq("contextual time reads an exact finite VNC without rewriting it",{status:contextual.authorizationStatus,reading:contextual.timeReading,formula:contextual.formulaRealization,written:contextual.surfaceRealization,sameFormula:contextual.formulaRealization===present.resultFrame.formulaRealization,sameWritten:contextual.surfaceRealization===present.resultFrame.surfaceRealization,changesMorphology:contextual.changesFiniteMorphology,copied:[copied.authorizationStatus,copied.blockReason]},{status:"authorized",reading:"historical-past",formula:present.resultFrame.formulaRealization,written:present.resultFrame.surfaceRealization,sameFormula:true,sameWritten:true,changesMorphology:false,copied:["blocked","owner-issued-finite-vnc-result-required"]});
const nounstems=NOUNSTEM_L.map(([stem])=>ordinary(ctx,stem));s.eq("the closed nounstem-l family enters ordinary NNC grammar directly",nounstems.map(({source,result})=>[source.stem,source.lexicalFormation,source.boundaryFacts.inferredNonactiveSource,result.authorizationStatus,result.formulaRealization,result.surfaceRealization]),NOUNSTEM_L.map(([stem,formula,written])=>[stem,"lexical-nounstem-l",false,"authorized",formula,written]));
const requiredOwners=["interpretClassicalNahuatlVncContextualTime","buildClassicalNahuatlValenceSourceAnalysis","evaluateClassicalNahuatlSupplementationOperation","buildClassicalNahuatlOrdinaryNncSourceFrame"];s.ok("Lesson 57 reuses typed owners without a generic analysis engine",requiredOwners.every(name=>typeof ctx[name]==="function")&&typeof ctx.evaluateClassicalNahuatlLesson57==="undefined"&&typeof ctx.evaluateClassicalNahuatlAnalysis==="undefined"&&!ctx.getClassicalGrammarApplicationInventory().operationIds.some(id=>id.startsWith("analysis:")));
const shell=fs.readFileSync(path.join(ROOT,"src/ui/shell/classical_shell.mjs"),"utf8"),rendering=fs.readFileSync(path.join(ROOT,"src/ui/rendering/rendering.mjs"),"utf8");s.ok("the interface keeps Lesson 57 inputs in the shared tense, ordinary-NNC, and supplementation paths",shell.includes('id="classical-rule-logic-tense"')&&shell.includes('data-classical-basal-unit="nnc"')&&rendering.includes('"contextual-silent-first-person": "contextualSilentFirstPerson"')&&rendering.includes('selectedRelation === "supplementation"'));
return s;}module.exports={run};
