"use strict";
const fs=require("fs"),path=require("path");const{createSuite}=require("./runner");const ROOT=path.resolve(__dirname,"..","..");
function ordinary(ctx,stem,{subject="3sg"}={}){const source=ctx.buildClassicalNahuatlOrdinaryNncSourceFrame({stem});const operation=ctx.buildClassicalNahuatlOrdinaryNncOperationFrame(source,{state:"absolutive",subject,sentenceType:"statement",polarity:"positive"});const receipt=ctx.executeClassicalGrammarApplicationRequest({operationId:"nnc:ordinary",args:[source,operation]});return ctx.buildClassicalComparisonSourceUnit({sourceResult:receipt.canonicalResult});}
function run(ctx={}){const s=createSuite("classical_lesson53_jobs");const ledger=JSON.parse(fs.readFileSync(path.join(ROOT,"docs/ANDREWS_ATOM_LEDGER.json"),"utf8"));const plan=JSON.parse(fs.readFileSync(path.join(ROOT,"docs/canvas-progress/lesson53-review-plan.json"),"utf8"));const field=Object.fromEntries(ledger.codebook.atomTuple.map((name,index)=>[name,index]));const atoms=ledger.atoms.filter(atom=>/^§53(?:\.|$)/u.test(atom[field.canvasSection]));const grammar=atoms.filter(atom=>atom[field.force]==="grammar-bearing");const roles=new Set(["canonical-rule-or-alternation","applicability-or-constraint","derived-realization","source-structure-schema","result-projection"]);const writing=grammar.filter(atom=>roles.has(atom[field.projectRole]));const mapped=new Set(plan.groups.flatMap(group=>group.sections));
s.eq("Lesson 53 partitions every Canvas atom into technical-proof groups",{atoms:atoms.length,grammar:grammar.length,writing:writing.length,readingOnly:atoms.length-writing.length,sections:[...new Set(atoms.map(atom=>atom[field.canvasSection]))],unmapped:atoms.filter(atom=>!mapped.has(atom[field.canvasSection])).map(atom=>atom[field.atomId])},{atoms:406,grammar:285,writing:230,readingOnly:176,sections:plan.groups.flatMap(group=>group.sections),unmapped:[]});
const ownerIds=[...new Set(grammar.map(atom=>atom[field.semanticOwnerId]))].sort();const observations=ownerIds.map(ownerId=>{const owned=grammar.filter(atom=>atom[field.semanticOwnerId]===ownerId);const source=fs.readFileSync(path.join(ROOT,owned[0][field.semanticOwnerReference]),"utf8");const spec=JSON.parse(source.match(/const spec = (\{[\s\S]*\});\nexport default/u)[1]);const results=Object.keys(spec.coordinates).map(key=>{const[selection,requestedFacet]=key.split("::");return ctx[`evaluate${spec.prefix}`](ctx[`build${spec.prefix}Source`]({analysisDomain:ownerId,selection,requestedFacet,participantChoice:`${selection}:${requestedFacet}`}));});return{atoms:owned.length,exact:source.includes(`"ownerId": "${ownerId}"`)&&results.every(result=>ctx[`is${spec.prefix}Result`](result)&&result.semanticOwnerId===ownerId&&["authorized","blocked"].includes(result.authorizationStatus))};});
s.eq("all grammar-bearing atoms retain exact semantic-owner proof",{atoms:observations.reduce((sum,item)=>sum+item.atoms,0),owners:observations.length,invalid:observations.filter(item=>!item.exact).length},{atoms:285,owners:35,invalid:0});
const gcd=ctx.buildClassicalComparisonGcdFrame(),lcm=ctx.getClassicalComparisonLcmInventory();s.eq("Lesson 53 reuses one comparison GCD with 23 routes and 31 axes",{gcd:gcd.gcdId,stages:gcd.orderedStages,routes:lcm.routeCount,axes:lcm.axisCount||lcm.distinctionAxisCount||lcm.axes?.length,lessonEvaluator:typeof ctx.evaluateClassicalNahuatlLesson53Comparison},{gcd:"typed-comparison-source-route-ast-result",stages:["typed-source","licensed-route","typed-operation","comparison-ast","canonical-result"],routes:23,axes:31,lessonEvaluator:"undefined"});
const cal=ordinary(ctx,"cal",{subject:"3common"}),mich=ordinary(ctx,"mich",{subject:"3common"}),teuc=ordinary(ctx,"tēuc"),honorific=ordinary(ctx,"yōlchicāhuacātzintli");const requests=[{routeId:"similarity-reduplicative-prefix",slots:{source:cal},choices:{continuationFamily:"absolutive-li"}},{routeId:"equality-iuhqui",slots:{comparand:cal,standard:mich},choices:{}},{routeId:"superlative-adverbial",slots:{topic:teuc,predicate:honorific},choices:{superlativeAdverbial:"cencah",sentenceType:"declarative"}}];const results=requests.map(request=>ctx.evaluateClassicalNahuatlComparison(request));
s.eq("similarity, equality, and superlative routes issue exact canonical Results",results.map(result=>({status:result.authorizationStatus,exact:ctx.isClassicalComparisonResultFrame(result),formulaAuthority:result.formulaStringAuthority,surfaceAuthority:result.surfaceStringAuthority})),Array(3).fill({status:"authorized",exact:true,formulaAuthority:false,surfaceAuthority:false}));
const batch=ctx.evaluateClassicalNahuatlComparisonBatch(requests);s.ok("batch comparison remains pointwise scalar-identical",batch.authorizationStatus==="authorized"&&batch.resultCount===3&&batch.pointwiseScalarEquality&&batch.formulaProjectionPointwiseScalarEquivalent&&batch.writtenProjectionPointwiseScalarEquivalent);
const copied={...cal};const blocked=ctx.evaluateClassicalNahuatlComparison({routeId:"equality-iuhqui",slots:{comparand:copied,standard:mich},choices:{lesson:53,surface:"display",formula:"display"}});s.ok("copied Sources and display metadata cannot authorize comparison",blocked.authorizationStatus==="blocked"&&!ctx.isClassicalComparisonResultFrame({...results[0]})&&!ctx.isClassicalComparisonResultFrame(JSON.parse(JSON.stringify(results[0]))));
const controller=fs.readFileSync(path.join(ROOT,"src/application/classical/clause_relation_controller.mjs"),"utf8"),rendering=fs.readFileSync(path.join(ROOT,"src/ui/rendering/rendering.mjs"),"utf8");s.ok("the live Clause composition workflow exposes all comparison routes from captured Results",controller.includes("getClassicalComparisonRouteInventory")&&controller.includes("requestClassicalComparisonResult")&&rendering.includes('decisionContract.relation === "comparison"'));
return s;}module.exports={run};
