"use strict";

const { createSuite } = require("./runner");

const entries = [
    ["ACI-P532-L025-6F5FA2D2EB-07", "ClassicalAdverbialAdjunctionCollocationTranslationAnalysis", "classical-adverbial-adjunction-collocation-translation-analysis", "claim-p4676", "p4676-as-in-the-particle-plus-particle-collocations-in-3", "analysis.translationCompositionAuthorizesStructure", false, "solid spelling not authorizing syntactic fusion"],
    ["ACI-P531-L005-F5369AF9B4", "ClassicalAdverbialAdjunctionMachRecursiveInterrogative", "classical-adverbial-adjunction-mach-recursive-interrogative", "claim-p4670", "p4670-inherently-interrogative-nncs-can-also-modify-a-structure-of", "analysis.inherentlyInterrogativeModifierMayModifyMachStructure", true, "an interrogative NNC modifying a mach structure"],
    ["ACI-P535-L002-B95FE8BD34-02", "ClassicalAdverbialAdjunctionModificationConjunctionContrast", "classical-adverbial-adjunction-modification-conjunction-contrast", "claim-p4690", "p4690-adverbial-collocations-created-by-modification-must-be-distinguished-from", "analysis.modificationAndConjunctionRemainSeparate", true, "modification remaining distinct from conjunction"],
    ["ACI-P529-L011-F6A4EF7BE2", "ClassicalAdverbialAdjunctionMultipleNucleusSimple", "classical-adverbial-adjunction-multiple-nucleus-simple", "claim-p4661", "p4661-a-simple-structure-of-adverbial-modification-need-not-be", "analysis.simpleAdjunctionAllowsMultipleNucleusUnits", true, "multiple nucleus units inside simple adverbial modification"],
    ["ACI-P533-L005-186002BDE9-02", "ClassicalAdverbialAdjunctionNegativeNimanIntensifier", "classical-adverbial-adjunction-negative-niman-intensifier", "claim-p4682", "p4682-the-adverbialized-nnc-niman-at-this-very-moment-now", "analysis.negativeScopeIntensifierLicensed", true, "niman intensifying negative scope"],
    ["ACI-P535-L017-3DF2A701D7", "ClassicalAdverbialAdjunctionPrincipalAdverbialConstruction", "classical-adverbial-adjunction-principal-adverbial-construction", "claim-p4693", "p4693-there-is-another-construction-involving-adverbial-nuclear-clauses-or", "analysis.adverbialClauseMayBePrincipalUnit", true, "an adverbial clause functioning as the principal unit"],
    ["ACI-P250-L026-C4A6D6EB0F", "ClassicalCompoundNncConjunctive", "classical-compound-nnc-conjunctive", "claim-p3114", "p3114-the-filler-of-the-first-conjunct-subposition-retains-a", "cases.conjunctive.rules.compound-nnc/conjunctive", true, "the conjunctive compound operation"],
    ["ACI-P303-L022-BCA7BCE0B5", "ClassicalCompoundNncDistributive", "classical-compound-nnc-distributive", "claim-p3127", "p3127-notice-the-difference-in-the-following-compound-stem-formations", "cases.distributive.rules.compound-nnc/distributive", true, "distributive derivation on a compound embed"],
    ["ACI-P585-L029-64F86C487F", "ClassicalDenominalVncYaRootRankSource", "classical-denominal-vnc-ya-root-rank-source", "claim-p4986", "p4986-to-form-a-denominal-verbstem-ya-is-attached-directly", "result.sourceKind", "nounroot-or-stem-as-root", "root-rank source selection for denominal ya"],
    ["ACI-P510-L002-20DAAD87CF", "ClassicalPlaceGentilicPlaceTopographicalBoundary", "classical-place-gentilic-place-topographical-boundary", "claim-p4564", "p4564-a-nahuatl-topographical-feature-name-frequently-serves-as-the", "analyses.topographicalBoundary.topographicalNameIsPlaceByDefault", false, "a topographical name not automatically being a place name"],
    ["ACI-P154-L029-4954F58738-02", "ClassicalSupplementationRecursiveClauseGraph", "classical-supplementation-recursive-clause-graph", "claim-p1809", "p1809-an-adjunctive-transformation-is-recursive-that-is-it-may", "extractedFrames.recursiveGraph.completeClauseNodeCount", 3, "recursive supplementation producing three clause nodes"],
    ["ACI-P289-L031-A4FE9FC1EF", "ClassicalIncorporatedComplementConsidering", "classical-incorporated-complement-considering", "claim-p3047", "p3047-in-addition-to-m-o-mati-and-te-mati", "cases.complementConsidering.rules.incorporated-complement/considering", true, "the incorporated complement considering relation"],
    ["ACI-P590-L009-05C642C95D-02", "ClassicalDenominalVncIncludedPossessorPronoun", "classical-denominal-vnc-included-possessor-pronoun", "claim-p5028", "p5028-this-means-that-a-possessor-pronoun-n-o-m", "result.operationId", "included-possessor-ti", "an included possessor inside a derived ti verbstem"],
    ["ACI-P188-L009-A409CB5183-02", "ClassicalImpersonalNonspecificObjectRetention", "classical-impersonal-nonspecific-object-retention", "claim-p2165", "p2165-the-nonspecific-projective-object-pronouns-te-and-tla-appearing", "voice.impersonalNonspecific.formulaRealization", "#0-0+tē(tla-zo-h-tla-lo)0+0-0#", "nonspecific human object retention in the impersonal"],
    ["ACI-P188-L021-3653DD917F-02", "ClassicalImpersonalReflexiveNeRetention", "classical-impersonal-reflexive-ne-retention", "claim-p2166", "p2166-when-generated-from-an-active-voice-transitive-source-that", "voice.reflexiveImpersonal.formulaRealization", "#0-0+ne(zahua-lo)0+0-0#", "reflexive ne retention in the impersonal"],
    ["ACI-P525-L029-800B09F748", "ClassicalPlaceGentilicExtensionTitle", "classical-place-gentilic-extension-title", "claim-p4652", "p4652-in-an-extension-of-meaning-somewhat-similar-to-that", "cases.title.lcmAxisId", "extension/title", "the place-linked title extension"],
    ["ACI-P521-L002-1A75BED69C", "ClassicalPlaceGentilicGentilicCaPanEca", "classical-place-gentilic-gentilic-ca-pan-eca", "claim-p4626", "p4626-place-name-nounstems-formed-on-pan-see-48-3", "cases.panEcaGentilic.lcmAxisId", "gentilic/ca-pan-eca", "the pan-eca gentilic construction"],
    ["ACI-P523-L009-87120F7709", "ClassicalPlaceGentilicGentilicDefectiveSpellingAmbiguity", "classical-place-gentilic-gentilic-defective-spelling-ambiguity", "claim-p4638", "p4638-for-example-the-defectively-written-ayotla-will-be-revealed", "analyses.defectiveSpelling.spellingSelectsFormation", false, "defective spelling not selecting a formation"],
    ["ACI-P256-L030-4950FDC4CC-02", "ClassicalIhcaCompoundMatrixFormation", "classical-ihca-compound-matrix-formation", "claim-p2803", "p2803-cho-ca-t-ihca-to-stand-crying", "cases.ihcaPreteritAsPresent.targetStem", "chōca-t-ih-ca", "ihca as an intransitive compound matrix"],
    ["ACI-P257-L021-64B1D00CD1", "ClassicalQuizaCompoundMatrixFormation", "classical-quiza-compound-matrix-formation", "claim-p2811", "p2811-tla-cui-ti-quiza-to-snatch-s-th", "cases.intransitiveMatrices.quiza.targetStem", "chōca-ti-quiza", "quiza as an intransitive compound matrix"],
    ["ACI-P600-L004-B9DC1212E1", "ClassicalDenominalVncTemporalTiaCategory", "classical-denominal-vnc-temporal-tia-category", "claim-p5109", "p5109-there-is-another-verbstem-fonning-suffix-tia-that-looks", "result.objectCount", 0, "the intransitive temporal tia category"],
    ["ACI-P599-L033-9B0E50C2A8", "ClassicalDenominalVncTiIaApplicativeFormation", "classical-denominal-vnc-ti-ia-applicative-formation", "claim-p5106", "p5106-a-few-intransitive-ti-verbstems-of-either-the-inceptive", "result.objectCount", 1, "applicative ti-ia adding one object"],
    ["ACI-P606-L006-3258AD3BB2-02", "ClassicalDenominalVncTransitiveIaSemantics", "classical-denominal-vnc-transitive-ia-semantics", "claim-p5149", "p5149-the-meaning-of-the-resultant-stem-is-to-cause", "result.operationId", "transitive-i-a", "the transitive i-a denominal operation"],
    ["ACI-P268-L033-EAB29C30B7-05", "ClassicalPurposiveMovementBaseAllomorphy", "classical-purposive-movement-base-allomorphy", "claim-p2903", "p2903-the-base-stem-to-which-the-directional-prefix-is", "cases.paradigmAxisExamples.eatFirstSingular.canonicalTranscriptionFormula", "#ni-Ø+tla(cuā-⎕-t-ī-uh)Ø+Ø-Ø#", "the exact purposive nitlacuātīuh formula"],
    ["ACI-P190-L013-B5096F7ABD-04", "ClassicalTransformedImpersonalDerivation", "classical-transformed-impersonal-derivation", "claim-p2143", "p2143-the-inherently-impersonal-constructions-of-22-1-do-not", "impersonal.tlaInventory.16.derivedTargetStem", "tla-cue-cuech-ca", "the derived tla-impersonal stem"],
    ["ACI-P200-L010-EB2EFD3CFA-04", "ClassicalTypeOneFinalAReplacement", "classical-type-one-final-a-replacement", "claim-p2296", "p2296-when-the-intransitive-stem-ends-in-a-the-type", "derivations.yocoya.options.0.targetStem", "yōco-y-a", "the exceptional yōcoya causative target"],
    ["ACI-P212-L013-323B7985E5-05", "ClassicalTypeTwoLtiaNiNaAlternation", "classical-type-two-ltia-ni-na-alternation", "claim-p2446", "p2446-the-ni-may-appear-as-ni-or-change-to", "derivations.cualani.options.4.targetStem", "cual-ā-n-tiā", "the cualāni nonactive-to-causative replacement"],
    ["ACI-P214-L017-334A9874AF-05", "ClassicalTypeTwoLtiaTiChiAlternation", "classical-type-two-ltia-ti-chi-alternation", "claim-p2452", "p2452-the-active-source-stem-ends-in-a-vowel-plus", "derivations.matiProjective.options.2.targetStem", "machi-l-tiā", "the machiltiā target stem"],
    ["ACI-P215-L009-93A3E85F7F-04", "ClassicalDenominalTiLiaCausative", "classical-denominal-ti-lia-causative", "claim-p2457", "p2457-those-verbstems-ending-in-i-that-take-lia-are", "derivations.mazati.options.2.targetStem", "mazā-ti-liā", "the denominal mazātiliā causative target"],
    ["ACI-P229-L013-040F89FE83-06", "ClassicalSingleObjectApplicativeTransform", "classical-single-object-applicative-transform", "claim-p2609", "p2609-when-the-source-is-an-intransitive-vnc-the-applicative", "formations.typeTwoFinalHui.option.targetStem", "tlatz-i-l-huiā", "the irregular related applicative formation"],
    ["ACI-P227-L026-7875BF00DF-04", "ClassicalDoubleObjectApplicativeTransform", "classical-double-object-applicative-transform", "claim-p2612", "p2612-when-the-source-is-a-single-object-vnc-the", "formations.parallelChihuaTypeOne.option.targetStem", "chīhu-iā", "the chīhuiā applicative target"],
    ["ACI-P233-L023-5910A6893A-04", "ClassicalRootFinalLOaHuiaApplicative", "classical-root-final-l-oa-huia-applicative", "claim-p2589", "p2589-when-o-a-participates-in-a-causative-destockal-verbstem", "formations.oaHistoryAHui.option.targetStem", "iht-a-l-huiā", "the ihtalhuiā applicative target"],
    ["ACI-P245-L040-2E226BDA67-07", "ClassicalTlaObjectPronounReduplication", "classical-tla-object-pronoun-reduplication", "claim-p2676", "p2676-in-instances-of-tla-fusion-see-7-10-the", "cases.fusedTlaAndStem.targetStem", "tlah-tla-coh-cōhua", "the independently reduplicated event-and-object stem"],
    ["ACI-P122-L033-AD59D5E8AD-02", "ClassicalPossessorNumberBoundaryFormation", "classical-possessor-number-boundary-formation", "claim-p1410", "p1410-for-the-third-person-it-manifests-number-the-morphic", "contractPossessorStateShapeInventory.3.st2", "o", "possessive-case o in st2"],
    ["ACI-P170-L017-34A93CB771-04", "ClassicalNegativeCommandFormation", "classical-negative-command-formation", "claim-p1089", "p1089-a-negative-command-sentence-or-a-negative-exhortation-sentence", "sentence.lesson9NegativeTransformation", "brusque-command-keeps-ah", "the negative-command transformation"],
    ["ACI-P160-L008-F169AFC15E-02", "ClassicalDiscontinuousSupplementLinearization", "classical-discontinuous-supplement-linearization", "claim-p1840", "p1840-it-frequently-happens-that-the-supplement-in-a-structure", "discontinuous.operationFrames.0.order", "discontinuous", "discontinuous supplement order"],
    ["ACI-P136-L032-C0EF66F166", "ClassicalDerivedNonanimatePossessiveReference", "classical-derived-nonanimate-possessive-reference", "claim-p1603", "p1603-a-possessive-state-nnc-may-be-formed-on-a", "mainFrame.inputClassGovernedFrame.lowerNncFrame.numberFrame.subjectNumber", "common", "common subject number in derived nonanimate possessives"],
    ["ACI-P156-L005-BDB8D8BC91-04", "ClassicalSupplementaryObjectBinding", "classical-supplementary-object-binding", "claim-p1801", "p1801-supplementary-object-the-personal-pronoun-subject-of-the-adjunct", "object.referenceFrame.headRole", "object", "the supplement binding to an object head"],
    ["ACI-P138-L018-AD36D954FB", "ClassicalSupplementaryPossessorBinding", "classical-supplementary-possessor-binding", "claim-p1803", "p1803-supplementary-possessor-the-personal-pronoun-subject-of-the-adjunct", "possessor.referenceFrame.headRole", "possessor", "the supplementary possessor role"],
    ["ACI-P153-L002-C48230781E-03", "ClassicalSupplementarySubjectBinding", "classical-supplementary-subject-binding", "claim-p1794", "p1794-supplementary-subject-the-personal-pronoun-subject-of-the-adjunct", "shared.referenceFrame.referenceIdentityUnified", true, "subject coreference across principal and supplement"],
    ["ACI-P165-L039-C65763AB07-03", "ClassicalVncSupplementaryPossessorBinding", "classical-vnc-supplementary-possessor-binding", "claim-p1907", "p1907-the-possessive-pronoun-i-oficol-and-the-object-pronoun", "vncPossessorSupplement.referenceFrame.headRole", "possessor", "the VNC supplementary possessor binding"],
    ["ACI-P155-L009-41781D3577-05", "ClassicalDemonstrativeSupplementation", "classical-demonstrative-supplementation", "claim-p1811", "p1811-the-demonstrative-pronominal-nncs-i-n-and-o-n", "demonstrativeSupplement.referenceFrame.headRole", "subject", "the demonstrative supplementary-subject role"],
    ["ACI-P169-L018-01BDC9D5AE-02", "ClassicalSpeechComplementSupplementation", "classical-speech-complement-supplementation", "claim-p1936", "p1936-verbstems-of-saying-questioning-etc-the-adjoined-sentence-can", "speech.referenceFrame.headRole", "object", "the quoted clause as supplementary object"],
    ["ACI-P213-L005-5A112863FE-06", "ClassicalSilentObjectSupplementationPrivilege", "classical-silent-object-supplementation-privilege", "claim-p2523", "p2523-it-has-the-same-privileges", "interactions.silentObjectSupplement.silentSpecificObjectAuthorized", true, "a grammatically present silent specific object"],
    ["ACI-P160-L018-06B6781A68-04", "ClassicalCollectiveSupplementAgreementException", "classical-collective-supplement-agreement-exception", "claim-p1845", "p1845-with-certain-nncs-whose-subject-personal-pronoun-is-apparently", "collective.referenceFrame.agreementException.licensed", true, "the collective agreement exception"],
    ["ACI-P160-L034-E885F2EC01-02", "ClassicalNamedPartnerSupplementException", "classical-named-partner-supplement-exception", "claim-p1849", "p1849-when-a-supplement-refers-to-a-plural-number-that", "namedPartner.referenceFrame.agreementException.licensed", true, "the named-partner agreement exception"],
    ["ACI-P161-L008-D74BE1E7E3-03", "ClassicalMaleBondingSupplementException", "classical-male-bonding-supplement-exception", "claim-p1851", "p1851-when-an-nnc-containing-the-nounstem-oquich-tli-is", "maleBonding.referenceFrame.agreementException.licensed", true, "the male-bonding supplement exception"],
    ["ACI-P155-L026-B44836033B", "ClassicalSupplementTopicLinearization", "classical-supplement-topic-linearization", "claim-p1817", "p1817-when-transposed-to-a-position-before-the-principal-the", "topic.operationFrames.1.topic", true, "a preposed supplement functioning as topic"],
    ["ACI-P166-L036-AB86455CD4", "ClassicalAcPronominalPluralCooperation", "classical-ac-pronominal-plural-cooperation", "claim-p1916", "p1916-these-three-questions-could-have-been-expressed-by-a", "acPlural.referenceFrame.headRole", "subject", "āc as a supplementary subject"],
    ["ACI-P156-L034-E86A8277DE", "ClassicalSupplementInformationQuestionFormation", "classical-supplement-information-question-formation", "claim-p1826", "p1826-information-questions-by-means-of-supplements", "informationQuestion.operationFrames.3.requiredPosition", "sentence-initial", "the interrogative supplement's required position"],
];

function getPath(value, path) {
    return path.split(".").reduce((current, key) => current?.[key], value);
}

function run(ctx = {}) {
    const s = createSuite("classical_checkpoint008_role_exact");
    for (const [atomId, prefix, domain, selection, facet, path, expected, description] of entries) {
        const source = ctx[`build${prefix}Source`]({
            analysisDomain: domain,
            selection,
            requestedFacet: facet,
            participantChoice: `${selection}:${facet}`,
        });
        const definition = ctx[`evaluate${prefix}`](source).payload.definition;
        const actual = { value: getPath(definition, path) };
        const wanted = { value: expected };
        s.eq(`${atomId} observes ${description}`, actual, wanted);
        const hostile = { value: typeof expected === "boolean" ? !expected : "BROKEN" };
        s.no(`${atomId} rejects a mutation of ${description}`, JSON.stringify(hostile) === JSON.stringify(wanted));
    }
    return s;
}

module.exports = { run };
