"use strict";const fs=require("fs"),path=require("path");const{createSuite}=require("./runner");const{auditClassicalNahuatlLessons5758Runtime}=require("./fixtures/classical_lessons57_58_source_ledger");const ROOT=path.resolve(__dirname,"..","..");
function run(ctx={}){const s=createSuite("classical_lesson58_jobs"),ledger=JSON.parse(fs.readFileSync(path.join(ROOT,"docs/ANDREWS_ATOM_LEDGER.json"),"utf8")),plan=JSON.parse(fs.readFileSync(path.join(ROOT,"docs/canvas-progress/lesson58-review-plan.json"),"utf8")),field=Object.fromEntries(ledger.codebook.atomTuple.map((name,index)=>[name,index])),atoms=ledger.atoms.filter(atom=>/^§58(?:\.|$)/u.test(atom[field.canvasSection])),grammar=atoms.filter(atom=>atom[field.force]==="grammar-bearing"),roles=new Set(["canonical-rule-or-alternation","applicability-or-constraint","derived-realization","source-structure-schema","result-projection"]),writing=grammar.filter(atom=>roles.has(atom[field.projectRole])),mapped=new Set(plan.groups.flatMap(group=>group.sections));
s.eq("Lesson 58 partitions every Canvas atom into technical-proof groups",{atoms:atoms.length,grammar:grammar.length,writing:writing.length,readingOnly:atoms.length-writing.length,sections:[...new Set(atoms.map(atom=>atom[field.canvasSection]))],unmapped:atoms.filter(atom=>!mapped.has(atom[field.canvasSection])).map(atom=>atom[field.atomId])},{atoms:500,grammar:268,writing:232,readingOnly:268,sections:plan.groups.flatMap(group=>group.sections),unmapped:[]});
const ownerIds=[...new Set(grammar.map(atom=>atom[field.semanticOwnerId]))].sort(),observations=ownerIds.map(ownerId=>{const owned=grammar.filter(atom=>atom[field.semanticOwnerId]===ownerId),source=fs.readFileSync(path.join(ROOT,owned[0][field.semanticOwnerReference]),"utf8"),spec=JSON.parse(source.match(/const spec = (\{[\s\S]*\});\nexport default/u)[1]);return{atoms:owned.length,exact:source.includes(`"ownerId": "${ownerId}"`)&&typeof ctx[`build${spec.prefix}Source`]==="function"&&typeof ctx[`evaluate${spec.prefix}`]==="function"&&typeof ctx[`is${spec.prefix}Result`]==="function"};});s.eq("all grammar-bearing atoms retain registered semantic owners",{atoms:observations.reduce((sum,item)=>sum+item.atoms,0),owners:observations.length,invalid:observations.filter(item=>!item.exact).length},{atoms:268,owners:23,invalid:0});
const audit=auditClassicalNahuatlLessons5758Runtime(ctx);s.eq("the existing typed owners execute the complete final lesson boundary",{complete:audit.complete,claims:audit.claimCount,executed:audit.authorizedExecutionCount,documentary:audit.diagnosticExecutionCount,failures:audit.failures},{complete:true,claims:54,executed:51,documentary:3,failures:[]});
const productionApis=["correctClassicalNahuatlText","normalizeClassicalNahuatlDocumentaryText","generateClassicalNahuatlTextualCorrection","requestClassicalNahuatlTextualCorrection"].filter(name=>typeof ctx[name]==="function");s.eq("Lesson 58 documentary reanalysis remains non-generative",{productionApis,analysisOperations:ctx.getClassicalGrammarApplicationInventory().operationIds.filter(id=>id.startsWith("analysis:")),lessonEvaluator:typeof ctx.evaluateClassicalNahuatlLesson58},{productionApis:[],analysisOperations:[],lessonEvaluator:"undefined"});
const requiredOwners=["evaluateClassicalNahuatlDenominalVnc","validateClassicalNahuatlClosedConstructionException","requestClassicalParticleResult","evaluateClassicalNahuatlSupplementationOperation","validateClassicalNahuatlIncorporatedNounRole"];s.ok("Lesson 58 reuses the canonical denominal, particle, supplementation, and incorporated-role owners",requiredOwners.every(name=>typeof ctx[name]==="function"));
const shell=fs.readFileSync(path.join(ROOT,"src/ui/shell/classical_shell.mjs"),"utf8"),rendering=fs.readFileSync(path.join(ROOT,"src/ui/rendering/rendering.mjs"),"utf8");s.ok("the shared interface delivers Lesson 58's genuine choices",shell.includes('value="denominal-vnc"')&&shell.includes('id="classical-built-in-particle"')&&shell.includes('data-classical-result-scope="sentence-introductory-particle"')&&rendering.includes('selectedRelation === "supplementation"'));
return s;}module.exports={run};
