// Presentation-only option inventory for the canonical place/gentilic evaluator.

const option = ({
  controlId,
  value,
  label,
  tagSuffix,
  lineStart,
  lineEnd,
  applicability,
  outputBehavior,
  canvasStatus = "authorized",
  selected = false,
  disabled = false,
  formationKind = "",
}) => Object.freeze({
  controlId,
  value,
  label,
  tagId: `cn-option-lesson48-${tagSuffix}`,
  canvasStatus,
  applicability,
  outputBehavior,
  transcriptionLineStart: lineStart,
  transcriptionLineEnd: lineEnd,
  exactWitness: `ANDREWS_TRANSCRIPTION_CANVAS.md:${lineStart}-${lineEnd}`,
  selected,
  disabled,
  formationKind,
  allowEmptyValue: value === "",
});

const kind = (value, label, tagSuffix, lineStart, lineEnd) => option({
  controlId: "classical-place-gentilic-result-kind",
  value,
  label,
  tagSuffix: `kind-${tagSuffix}`,
  lineStart,
  lineEnd,
  applicability: "typed place/gentilic construction family",
  outputBehavior: "selects a canonical place, gentilic, or licensed extension evaluator branch",
});

const formation = (value, label, tagSuffix, lineStart, lineEnd, formationKind) => option({
  controlId: "classical-place-gentilic-formation",
  value,
  label,
  tagSuffix: `formation-${tagSuffix}`,
  lineStart,
  lineEnd,
  applicability: `typed ${formationKind} source`,
  outputBehavior: "selects a boundary operation; the evaluator derives the result",
  formationKind,
});

export const PLACE_GENTILIC_NNC_UI_CONTROL_CONTRACTS = Object.freeze({
  "classical-construction-operation": Object.freeze([
    option({
      controlId: "classical-construction-operation",
      value: "place-gentilic-nnc",
      label: "place-name or gentilic NNC",
      tagSuffix: "construction",
      lineStart: 19929,
      lineEnd: 19931,
      applicability: "typed place-name or gentilic source",
      outputBehavior: "routes the request to the canonical place/gentilic evaluator",
    }),
  ]),
  "classical-place-gentilic-result-kind": Object.freeze([
    kind("place-name", "place-name NNC", "place", 19931, 20012),
    kind("gentilic", "gentilic NNC", "gentilic", 20361, 20579),
    kind("gentilic-collective", "gentilic collectivity", "collective", 20629, 20666),
    kind("profession-place-association", "profession or title", "profession-title", 20667, 20706),
    kind("profession-pertinency", "profession pertinency", "profession-pertinency", 20667, 20680),
    kind("gentilic-adjectival-use", "adjectival gentilic use", "adjectival", 20619, 20628),
  ]),
  "classical-place-gentilic-formation": Object.freeze([
    formation("n-imperfect-active", "n · active imperfect predicate", "n-imperfect-active", 20013, 20030, "place-name"),
    formation("n-imperfect-nonactive", "n · nonactive imperfect predicate", "n-imperfect-nonactive", 20031, 20038, "place-name"),
    formation("n-yan", "yā-n place", "n-yan", 20039, 20044, "place-name"),
    formation("n-man", "mā-n area", "n-man", 20049, 20056, "place-name"),
    formation("n-tlan-vicinity", "tlā-n vicinity", "n-tlan", 20057, 20105, "place-name"),
    formation("n-can", "cā-n place", "n-can", 20106, 20130, "place-name"),
    formation("n-preterit-agentive", "preterit-agentive cā-n", "n-agentive", 20131, 20174, "place-name"),
    formation("n-action-noun", "action-noun cā-n", "n-action", 20175, 20192, "place-name"),
    formation("pan-integrated", "integrated pan", "pan", 20193, 20217, "place-name"),
    formation("pan-connective-t", "connective-t pan", "pan-connective", 20218, 20232, "place-name"),
    formation("co", "co", "co", 20233, 20261, "place-name"),
    formation("c", "c", "c", 20288, 20303, "place-name"),
    formation("co-affective-embed", "affective embed + co", "co-affective-embed", 20262, 20269, "place-name"),
    formation("co-place-affective", "place + tzin/tōn + co", "co-place-affective", 20270, 20287, "place-name"),
    formation("co-compound-nahuac", "compound nāhua-c", "compound-nahuac", 20304, 20321, "place-name"),
    formation("co-compound-ixco", "compound ix-co", "compound-ixco", 20304, 20321, "place-name"),
    formation("co-compound-ticpac", "compound t-icpa-c", "compound-ticpac", 20304, 20321, "place-name"),
    formation("tlah", "abundance tlah", "tlah", 20322, 20329, "place-name"),
    formation("tlah-pan", "pan embedded in tlah", "tlah-pan", 20330, 20334, "place-name"),
    formation("tzalan", "tzālan", "tzalan", 20335, 20338, "place-name"),
    formation("ti-tlan", "connective-t tlan", "ti-tlan", 20339, 20343, "place-name"),
    formation("chan-supplementation", "chān possessor supplementation", "chan", 20344, 20360, "place-name"),
    formation("gentilic-incorporated-place", "gentilic embed + place matrix", "gentilic-place", 20580, 20618, "place-name"),
    formation("gentilic-affective-co", "affective gentilic + co", "gentilic-affective", 20580, 20618, "place-name"),
    formation("nonlocative-absolutive", "nonlocative tribal gentilic", "tribal", 20361, 20375, "gentilic"),
    formation("two-clause-concatenate", "two-clause gentilic", "two-clause", 20376, 20411, "gentilic"),
    formation("preterit-agentive-owner", "ownerhood agentive gentilic", "agentive-owner", 20412, 20426, "gentilic"),
    formation("preterit-agentive-other", "other agentive gentilic", "agentive-other", 20427, 20441, "gentilic"),
    formation("ca-full-place", "full place + ca", "ca-full", 20442, 20457, "gentilic"),
    formation("ca-pan-eca", "pan + ē-ca", "ca-pan", 20458, 20481, "gentilic"),
    formation("ca-can-meca", "cā-n + m-ē-ca", "ca-can", 20482, 20495, "gentilic"),
    formation("ca-co-c-silent", "co/c replacement + ca", "ca-co-c", 20496, 20520, "gentilic"),
    formation("ca-ownerhood-n-silent", "ownerhood cā-n replacement + ca", "ca-owner", 20524, 20539, "gentilic"),
    formation("ca-man-tlan-teca", "mā-n/tlā-n → mē-ca/tē-ca", "ca-man-tlan", 20540, 20557, "gentilic"),
  ]),
  "classical-gentilic-source-place-matrix": Object.freeze([
    option({ controlId: "classical-gentilic-source-place-matrix", value: "", label: "not applicable", tagSuffix: "place-matrix-none", lineStart: 20496, lineEnd: 20520, applicability: "formation does not replace co or c", outputBehavior: "does not supply a place matrix", canvasStatus: "not-applicable" }),
    option({ controlId: "classical-gentilic-source-place-matrix", value: "co", label: "co", tagSuffix: "place-matrix-co", lineStart: 20496, lineEnd: 20520, applicability: "co place source", outputBehavior: "licenses co replacement before gentilic ca" }),
    option({ controlId: "classical-gentilic-source-place-matrix", value: "c", label: "c", tagSuffix: "place-matrix-c", lineStart: 20496, lineEnd: 20520, applicability: "c place source", outputBehavior: "licenses c replacement before gentilic ca" }),
  ]),
  "classical-place-affective-analysis": Object.freeze([
    option({ controlId: "classical-place-affective-analysis", value: "", label: "analysis required", tagSuffix: "analysis-none", lineStart: 20270, lineEnd: 20287, applicability: "surface-identical analysis remains unresolved", outputBehavior: "blocks ambiguous affective generation", canvasStatus: "blocked" }),
    option({ controlId: "classical-place-affective-analysis", value: "place-name-affective", label: "place name + affective", tagSuffix: "analysis-place-affective", lineStart: 20270, lineEnd: 20282, applicability: "typed place-name plus affective structure", outputBehavior: "silences the inner co and embeds the affective stem in co" }),
    option({ controlId: "classical-place-affective-analysis", value: "lexical-affective", label: "affective nounstem + co", tagSuffix: "analysis-lexical-affective", lineStart: 20262, lineEnd: 20287, applicability: "typed lexical affective embed", outputBehavior: "embeds the affective nounstem directly in co" }),
  ]),
  "classical-place-affective-matrix": Object.freeze([
    option({ controlId: "classical-place-affective-matrix", value: "tzin", label: "tzin", tagSuffix: "affective-tzin", lineStart: 20262, lineEnd: 20287, applicability: "typed affective formation", outputBehavior: "selects the tzin affective matrix" }),
    option({ controlId: "classical-place-affective-matrix", value: "tōn", label: "tōn", tagSuffix: "affective-ton", lineStart: 20262, lineEnd: 20287, applicability: "typed affective formation", outputBehavior: "selects the tōn affective matrix" }),
  ]),
  "classical-place-gentilic-lexical-record": Object.freeze([
    option({ controlId: "classical-place-gentilic-lexical-record", value: "", label: "record required", tagSuffix: "lexical-none", lineStart: 20667, lineEnd: 20706, applicability: "no closed record selected", outputBehavior: "blocks lexical extension generation", canvasStatus: "blocked" }),
    ...[
      ["toltec-craftsman", "Toltec craftsman", "profession-toltec"],
      ["amantec-feather-worker", "Amantec feather worker", "profession-amantec"],
      ["pochtec-merchant", "Pochtec merchant", "profession-pochtec"],
      ["oztomec-vanguard-merchant", "Oztomec vanguard merchant", "profession-oztomec"],
    ].map(([value, label, tagSuffix]) => option({ controlId: "classical-place-gentilic-lexical-record", value, label, tagSuffix, lineStart: 20667, lineEnd: 20680, applicability: "closed lexical profession record", outputBehavior: "selects the recorded profession stem" })),
    ...[
      ["tlacochcalcatl", "tlacōchcalcatl title", "title-tlacochcalcatl", false],
      ["tlacateccatl", "tlācatēccatl title", "title-tlacateccatl", false],
      ["tocuiltecatl", "tocuiltēcatl title", "title-tocuiltecatl", false],
      ["atempanecatl", "ātēmpanēcatl title", "title-atempanecatl", false],
      ["tezcacoacatl", "tezcacōācatl title", "title-tezcacoacatl", false],
    ].map(([value, label, tagSuffix]) => option({ controlId: "classical-place-gentilic-lexical-record", value, label, tagSuffix, lineStart: 20681, lineEnd: 20706, applicability: "closed lexical title record with typed formula", outputBehavior: "selects the recorded title stem" })),
  ]),
});
