const idea=(ideaId,title,guidance)=>Object.freeze({ideaId,title,guidance});export const LESSON58_READER_GUIDANCE_GROUPS=Object.freeze([
idea("lesson58-instrumental-denominals","Instrumental -āz has licensed continuations","A typed lexical NNC Source may continue through huiā or o-ā only where its denominal owner licenses that path."),
idea("lesson58-closed-constructions","Closed constructions do not become productive rules","Retained material, solid spelling, connective t, matrix-object control, and frozen reflexives require their exact licensed structures."),
idea("lesson58-exclamations-and-haste","Exclamations preserve the particle unit","Frozen haste expressions and licensed pronoun variants remain exact particle Results inside an exclamatory utterance."),
idea("lesson58-vocative-e","Vocative e attaches outside an exact unit","The vocative boundary changes utterance use without flattening or rebuilding the unit's internal grammar."),
idea("lesson58-mah-system","mah and wish mā remain separate","Typed particle identity, optional in, and principal polarity determine the mah relation; spelling and translation do not."),
idea("lesson58-such-that-principals","Such-that relations keep exact principals","quemah ellipsis and cuix, ahzo, ahmo, iuhqui, or iuh principals require owner-issued principal, marker, and supplement units."),
idea("lesson58-incorporated-noun-roles","An incorporated noun is never the subject","Active incorporation is adverbial; nonactive incorporation may express means or instrument, while personal subjects and passive-agent barriers remain."),
idea("lesson58-documentary-reanalysis","Documentary corrections explain but never generate","Textual corrections, vocable boundaries, and sentence redivision remain diagnostic evidence with no production authority."),
]);export function isLesson58ReaderGuidanceExact(candidate=[]){return JSON.stringify(candidate)===JSON.stringify(LESSON58_READER_GUIDANCE_GROUPS);}export function renderLesson58ReaderGuidance(escapeHtml=String){return `<details class="classical-reader-guidance__lesson" data-classical-reader-guidance-lesson="58"><summary class="classical-reader-guidance__lesson-summary"><span>Lesson 58</span><small>Construction boundaries</small></summary><div class="classical-reader-guidance__lesson-body"><div class="classical-reader-guidance__grid">${LESSON58_READER_GUIDANCE_GROUPS.map(group=>`<section class="classical-reader-guidance__card" data-classical-reader-guidance-group="${escapeHtml(group.ideaId)}"><h5 class="classical-reader-guidance__title">${escapeHtml(group.title)}</h5><p data-classical-reader-guidance-idea="${escapeHtml(group.ideaId)}">${escapeHtml(group.guidance)}</p></section>`).join("")}</div></div></details>`;}
