const idea=(ideaId,title,guidance)=>Object.freeze({ideaId,title,guidance});export const LESSON55_READER_GUIDANCE_GROUPS=Object.freeze([
idea("lesson55-temporal-tia","Temporal tiā begins with a time-segment Source","The typed compound NNC Source licenses an intransitive temporal Result; spelling does not merge it with transitive tia formations."),
idea("lesson55-tla-verbalizations","Causative and intransitive tla remain distinct","Each tla route keeps its own Source meaning, transitivity, participants, class, and licensed continuation."),
idea("lesson55-oa-huia-pair","o-ā and huiā coordinate meaning with valence","Use and production readings align with intransitive o-ā or applicative huiā while object structure stays explicit."),
idea("lesson55-adverbial-huia","Adverbial huiā preserves Source rank","Only a typed adverbial nounstem enters this route; its class, valence, and finite realization are derived canonically."),
idea("lesson55-relational-denominals","Relational Sources survive verbalization","Relational structure remains present while o-ā or huiā projects the licensed participant and valence pattern."),
idea("lesson55-ihui-ahui-causatives","Causatives consume exact i-hui or a-hui Results","The Class B upstream Result must be exact and eligible before a Class C o-ā causative can be issued."),
idea("lesson55-transitive-ia","Surface i does not decide the i-ā analysis","Typed Source rank distinguishes stock i, supportive i, inherited i, and competing huiā structures before transitive realization."),
]);export function isLesson55ReaderGuidanceExact(candidate=[]){return JSON.stringify(candidate)===JSON.stringify(LESSON55_READER_GUIDANCE_GROUPS);}export function renderLesson55ReaderGuidance(escapeHtml=String){return `<details class="classical-reader-guidance__lesson" data-classical-reader-guidance-lesson="55"><summary class="classical-reader-guidance__lesson-summary"><span>Lesson 55</span><small>Denominal verbstems, part two</small></summary><div class="classical-reader-guidance__lesson-body"><div class="classical-reader-guidance__grid">${LESSON55_READER_GUIDANCE_GROUPS.map(group=>`<section class="classical-reader-guidance__card" data-classical-reader-guidance-group="${escapeHtml(group.ideaId)}"><h5 class="classical-reader-guidance__title">${escapeHtml(group.title)}</h5><p data-classical-reader-guidance-idea="${escapeHtml(group.ideaId)}">${escapeHtml(group.guidance)}</p></section>`).join("")}</div></div></details>`;}
